## Basic Configuration

baseurl = "https://danielkeyesdev.pages.dev/" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Daniel Keyes"
title = "Daniel Keyes"

theme = "hugo-goa"

[markup.goldmark.renderer]
hardWraps= true
unsafe= true

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = ""
enableRobotsTXT = true

## Site Settings
[params]
author = "Daniel Keyes"
intro = "Software Developer (Android/Kotlin/Java)"
description = "I currently do Android native development for a financial institution"
authorimage = "SquareProfile.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "android,kotlindeveloper,danielkeyes"

## Social Accounts
[params.social]
github = "danielkeyes"
linkedin = "danielkeyesdev"
twitter = "danielkeyesdev"
email = "daniel@danielkeyes.dev"

## Extras
[params.extra]
copyright = "© 2022. Daniel Keyes. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "About Me" 
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "The Reveal"
    identifier = "thereveal"
    weight = 300
    url = "/thereveal/"